
spring:

  main:
    allow-bean-definition-overriding: true

  profiles:
    include: oauth

  server:
    port: 8080
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  # db ??
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # jpa ??
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #show_sql: true

# logging ??
logging.level:
  org.hibernate.SQL: debug
  ##org.hibernate.type: trace
